# Generated by Django 3.2.6 on 2024-04-27 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.PositiveIntegerField()),
                ('projects', models.PositiveIntegerField()),
                ('hours_of_support', models.CharField(max_length=20)),
                ('hard_work', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your fullname', max_length=100)),
                ('position', models.CharField(help_text='Occupation', max_length=50)),
                ('image', models.FileField(null=True, upload_to='teams')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Clien name', max_length=40)),
                ('position', models.CharField(help_text='Occupation', max_length=40)),
                ('advice', models.TextField(help_text='description')),
                ('image', models.FileField(blank=True, null=True, upload_to='clients')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Web1, Web2, App1, Bot1, Card1', max_length=10)),
                ('category', models.CharField(choices=[('APP', 'APP'), ('CARD', 'CARD'), ('WEB', 'WEB'), ('BOT', 'BOT')], max_length=4)),
                ('image', models.FileField(blank=True, upload_to='portfolio')),
                ('name', models.CharField(help_text='Category name, Web design, Graphic', max_length=100)),
                ('client', models.CharField(help_text='Client name or organisation', max_length=50)),
                ('project_date', models.CharField(blank=True, max_length=255, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('project_title', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='file/')),
                ('desc', models.TextField(help_text='about project', null=True)),
                ('images', models.ManyToManyField(blank=True, null=True, to='portfolio.Images')),
                ('workers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
