# Generated by Django 5.0.4 on 2024-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startteam', '0002_telegram_team_team_lead_alter_orders_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
