# Generated by Django 5.0.4 on 2024-04-27 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startteam', '0004_remove_projects_workers_id_projects_workers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='workers_id',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
