# Generated by Django 3.2.6 on 2024-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startteam', '0005_alter_projects_workers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='desc_to_workers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
